FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PYTHONPATH="/app/src"
EXPOSE 8080
CMD ["uvicorn", "src.app.api:app", "--host", "0.0.0.0", "--port", "8080"]